### ISSUE TITLE
docker build failed for echopype v0.3.1

### ISSUE THREAD

**Issue by leewujung** [conda-forge/echopype-feedstock#5]
Docker build failed for echopype v0.3.1 when trying to import echopype. 
It complains about `ModuleNotFoundError: No module named 'zarr'` [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=147874&view=logs&j=e018f978-a0ce-53fb-9fb6-ffd586bfca01&t=5c69329b-d947-5705-66b5-610e0963c1aa&l=732), but I am not sure where I can specify that outside of `environment.yml` and `requirements.txt`.

@ocefpaf : I am making a new issue here per @emiliom 's recommendation, in addition to the one in the echopype repo.  Thanks!

**Comment by emiliom** [comment]
To add to @leewujung's info, `zarr` is specified in both [environment.yml](https://github.com/OSOceanAcoustics/echopype/blob/master/environment.yml) and [requirements.txt](https://github.com/OSOceanAcoustics/echopype/blob/master/requirements.txt). I can see in the [Azure DevOps Run docker build log](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=147874&view=logs&j=e018f978-a0ce-53fb-9fb6-ffd586bfca01&t=5c69329b-d947-5705-66b5-610e0963c1aa&l=630) that `zarr` is not among the packages installed by conda. But I also see other packages from environment.yml and requirements.txt that are also not installed, including `dask`, `ipykernel`, `numpydoc` and `pynmea2`.

Also, tests locally and on GitHub through travis both work.

ref https://github.com/conda-forge/echopype-feedstock/pull/4, https://github.com/OSOceanAcoustics/echopype/issues/127  and maybe https://github.com/OSOceanAcoustics/echopype/issues/59 (old)

**Comment by leewujung** [comment]
Ugh, it just became painfully obvious that zarr is not in the recipe so obviously the import wouldn't work... 😭  Let me give it a try!

**Comment by ocefpaf** [comment]
> Ugh, it just became painfully obvious that zarr is not in the recipe so obviously the import wouldn't work...  Let me give it a try!

I'll send a PR to try to help you manage this.

**Comment by leewujung** [comment]
Thanks @ocefpaf !  Seems like my PR to the bot's branch following the maintaining packages instruction worked: https://github.com/conda-forge/echopype-feedstock/pull/6 
Should I just merge? Are there other things I should pay attention to?

**Comment by ocefpaf** [comment]
Yep. Just merged it. But I'm sending a PR upstream that will make it easier to manage deps.

**Comment by emiliom** [comment]
Great to see the fix was easy (even if a bit embarrassing :laughing:), and that a conda package is now available!
